### ISSUE TITLE
Feature request: Storing credentials for private registries in config file

### ISSUE THREAD

**Issue by danmx** [target/portauthority#21]
It would be great if PA could store credentials for private registries so we wouldn't have to send them every time we run a scan.

Similar to what K8 Crawler.

**Comment by ErikThoreson** [comment]
@danmx thanks for the feedback. internally we handle this by leveraging a client utility that runs as a k8s cronjob and calls the api on schedule. That utility allows env's to for those creds.

Would something like that be useful?
