### ISSUE TITLE
Feature request: Handling environment variables in config file

### ISSUE THREAD

**Issue by danmx** [target/portauthority#22]
It would be perfect if we could use environment variables to pull parts of the configuration, e.g. DB or registry credentials.

**Comment by ErikThoreson** [comment]
Hi @danmx,

What env's specifically would you like to see?

For DB configuration you can leverage any of the available postgresql env's.

https://www.postgresql.org/docs/9.6/static/libpq-envars.html

For the registry creds see the other feature request you posted.
