### ISSUE TITLE
Clair copyright?

### ISSUE THREAD

**Issue by chancez** [target/portauthority#4]
First off, this project is awesome, I really look forward to giving it a try, and seeing it grow.

However, I noticed some of the code in this project uses code from github.com/coreos/clair, this is awesome! That being said, it would be great if you could include the original copyright since you're re-using some of the code. If you've made changes, to the original file you can definitely add your copyright after the original. Additionally, the original project contains a NOTICE file (https://github.com/coreos/clair/blob/master/NOTICE) which you must include as well. 

I noticed when looking at https://github.com/target/portauthority/commit/c12f84ead5edbc348f76c20a4cf932dac32395ba#diff-604f4192deea5adf9c159e5f88f64630R1 and comparing it to https://github.com/coreos/clair/blob/release-2.0/api/api.go

Thanks!

**Comment by Quentin-M** [comment]
Thanks @chancez. And thanks for making this project, which has been long awaited.

Original author Clair here, I am also a bit saddened to see so much code (sometimes entire packages) being copy-pasted without credits or respecting copyright.

**Comment by ErikThoreson** [comment]
@chancez @Quentin-M we definitely used a lot of code from Clair to model this project on and want your project to be success as we couldn't be able to offer this one with out it. Would adding the copy write to each file we used like @chancez suggested suffice?

**Comment by ErikThoreson** [comment]
This is what I'm thinking

https://github.com/target/portauthority/pull/5
